### ISSUE TITLE
Icons widget

### ISSUE THREAD

**Issue by AndreMiras** [fatiherikli/mockup-designer#12]
Being able to add icons to mockups would be great.
I thought we could use [Font-Awesome](http://fortawesome.github.io/Font-Awesome/) to achieve it, even though I don't like using too many dependencies.
Let me know what do you think.

**Comment by jdittrich** [comment]
Could we not implement this as a custom widget? It could check if the resources are available and only displays if they are or displays some error message.

**Comment by bittner** [comment]
:+1: for Font-Awesome

@jdittrich I don't understand your custom widget approach. Is this meat to be a generalized widget that  can, e.g., integrate Font-Awesome?

**Comment by AndreMiras** [comment]
Yes we could provide something generic for linking to any external CSS. While I like the idea of not bringing one more dependency, it would still make things lot more easier to use and to implement if the dependency is already there.
It would be great to have @fatiherikli advice.

**Comment by AndreMiras** [comment]
I think we can ignore the first feature branch I've worked on (feature/fontawesome_icons_widget). It was using a dedicated widget.
But I actually prefer the other approach (feature/fontawesome_support) which just adds the FontAwesome dependency. Then you can use it anywhere. For example in a "Label" widget, just put the usual FontAwesome HTML code within the "text" input field.
See #24 for implementation details.

**Comment by AndreMiras** [comment]
Merged, see #24
